version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 400M
    command: redis-server --port 6382 --maxmemory 300mb --maxmemory-policy allkeys-lru --appendonly no

  api:
    image: ${DOCKER_USERNAME}/notification_service_backend:latest
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    env_file: .env

  worker:
    image: ${DOCKER_USERNAME}/notification_service_backend:latest
    command: ["node", "dist/worker.js"]
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    env_file: .env

volumes:
  mongo_data:
